ocelot-ide/ElementaryJS

test/unit-tests.test.ts, ts/runtime.ts, ts/types.ts
- Unit Testing for EJS Testing
- Minor changes on testing to allow for no styles in testing
- A bit of documentation for EJS Testing
=> Added unit testing for EJS testing and documentation

ts/lib220.ts
- `ImageData` class
- `createImage` function for creating Images rather than load image from url
- fixed `image.copy()`
=> node support for lib220

test/unit-tests.test.ts, ts/runtime.ts, ts/timeout.ts
=> timing out non-online tests

ts/lib220.ts, ts/runtime.ts
This was a bug waiting to happen.
=> Remove duplicate reference to runner

ts/lib220.ts
- No optionals -  require fill parameter for `lib220.createImage`
=> No optional parameters for lib220

test/unit-tests.test.ts, ts/timeout.ts, ts/visitor.ts
=> if else block static check + unit tests

test/unit-tests.test.ts, ts/visitor.ts
- break and continue statement static check
=> break and continue statement static check

ts/lib220.ts
Example usage:
```js
c = lib220.newCanvas(600, 600);
c.drawArc(300, 300, 200, 0, 2 * Math.PI, [0.8, 0.4, 0]);
for (let i = 0; i < 100; ++i) {
const a = i / 100 * Math.PI;
const x = 200 * Math.cos(a);
const y = 200 * Math.sin(a);
c.drawLine(300 + x, 300 + y, 300 - x,
300 - y, [1, 0.5, 0]);
}
```
=> Added native canvas drawing

package.json, test/unit-tests.test.ts, yarn.lock
Upgraded Stopify version that has workaround
=> Version 1.0.4

ts/lib220.ts
- Check pixel values are numbers
=> Check number in assertValidPixel in lib220

ts/lib220.ts
- Added `loadJSONFromURL`
- Added a `loadURLHandler` to not repeat code
=> Added loadJSONFromURL

package.json
=> Bump to 1.0.6

ts/index.ts, ts/lib220.ts, ts/runtime.ts
- `stopifyObjectArrayRecur` function that recurs into an object/array
- Fixed `JSON.parse`
- Fixed `loadJSONFromURL`
=> stopify JSON.parse output and stopify loadJSONFromURL

package.json
=> Bump to 1.0.9

ts/lib220.ts
- added `lib220.sleep`
- does not return anything (`undefined`)
=> added sleep function in lib220

ts/lib220.ts
- added `lib220.input` function that prompts user for input
- returns empty string if no given input, otherwise returns user's given input
- returns `'user input is disabled'` string when not called in browser
=> added input function to lib220

package.json, yarn.lock
- Bump project interpreter version to 1.1.4
=> Bump project interpreter version to 1.1.4

package.json
=> Bump to 1.0.19

test/unit-tests.test.ts, ts/index.ts
=> Add Infinity

package.json, test/unit-tests.test.ts, ts/index.ts, ts/runtime.ts, ts/visitor.ts, yarn.lock
Merge and rebuild after Stopify is published.
=> Changes to track the latest version of Stopify

src/index.ts, tests/ejs.test.ts
I think this was always intended, but never tested. Closes #202.
=> Support JSON.stringify
